**Bag of Words**

  * Words into numerical form

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

docs = [
    "I am a good Cricket player",
    "Rajiv is a bad Chess player"
]

vectorizer = CountVectorizer()
bow_matrix =  vectorizer.fit_transform(docs)
#print(vectorizer.get_feature_names_out())

pd.DataFrame(bow_matrix.toarray() , columns=vectorizer.get_feature_names_out())

am  bad  chess  cricket  good  is  player  rajiv
0   1    0      0        1     1   0       1      0
1   0    1      1        0     0   1       1      1

**TFiD vectorizer**

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

docs = [
    "AI is the future",
    "AI and ML are the future",
    "Physics is really intersting thing",
    "I am intrested in concepts of physics"
]

In [3]:
vectorizer = TfidfVectorizer()
tfid_matrix = vectorizer.fit_transform(docs)

In [4]:
vectorizer.get_feature_names_out()

array(['ai', 'am', 'and', 'are', 'concepts', 'future', 'in', 'intersting',
       'intrested', 'is', 'ml', 'of', 'physics', 'really', 'the', 'thing'],
      dtype=object)

In [5]:
import numpy as np
import pandas as pd

pd.DataFrame(tfid_matrix.toarray() , columns = vectorizer.get_feature_names_out())

ai        am       and       are  concepts    future        in  \
0  0.500000  0.000000  0.000000  0.000000  0.000000  0.500000  0.000000   
1  0.357455  0.000000  0.453386  0.453386  0.000000  0.357455  0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.421765  0.000000  0.000000  0.421765  0.000000  0.421765   

   intersting  intrested        is        ml        of   physics    really  \
0    0.000000   0.000000  0.500000  0.000000  0.000000  0.000000  0.000000   
1    0.000000   0.000000  0.000000  0.453386  0.000000  0.000000  0.000000   
2    0.485461   0.000000  0.382743  0.000000  0.000000  0.382743  0.485461   
3    0.000000   0.421765  0.000000  0.000000  0.421765  0.332524  0.000000   

        the     thing  
0  0.500000  0.000000  
1  0.357455  0.000000  
2  0.000000  0.485461  
3  0.000000  0.000000

**Tokenization & Word embedding**

  * Tokenization is the process of breaking a sentence or paragraph into smaller units called tokens usually words or subwords.

  * **Integer encoding** - After tokenization, we convert each unique word into integer ID, SO that it can be used for predictive modelling or in a neural network

In [6]:
from tensorflow.keras.preprocessing.text import Tokenizer


texts = [
    "I am playing good cricket",
    "He is playing chess",
]

#Initialize the tokenizer
tokenizer = Tokenizer()

#Fit the text on tokenizer
tokenizer.fit_on_texts(texts)

#View the word index
print(tokenizer.word_index)

{'playing': 1, 'i': 2, 'am': 3, 'good': 4, 'cricket': 5, 'he': 6, 'is': 7, 'chess': 8}


In [7]:
#Convert text to sequence of integers
sequences = tokenizer.texts_to_sequences(texts)
print(sequences)

[[2, 3, 1, 4, 5], [6, 7, 1, 8]]


In [8]:
from keras.utils import pad_sequences
padded_sequences = pad_sequences(sequences , padding='post')
padded_sequences

array([[2, 3, 1, 4, 5],
       [6, 7, 1, 8, 0]], dtype=int32)

In [9]:
from keras.utils import to_categorical
to_categorical(padded_sequences)

array([[[0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0.]]])

**Keras embedding**

In [10]:
from tensorflow.keras import models, layers

model = models.Sequential()
model.add(layers.Embedding(input_dim = 9 , output_dim = 4, input_length=5))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile('adam' , 'accuracy')
word_vectors = model.predict(padded_sequences)
word_vectors

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 925ms/step


array([[[ 0.0003153 , -0.02007775,  0.00180835, -0.0115082 ],
        [ 0.02896477, -0.04479357, -0.04676715,  0.02114597],
        [ 0.01898329, -0.03323045,  0.04401389,  0.01882345],
        [-0.00077549, -0.00180267,  0.00038796, -0.02173099],
        [-0.025114  ,  0.01354594, -0.04560959,  0.00674785]],

       [[ 0.04745657, -0.03038027, -0.00270725, -0.02514657],
        [ 0.00937791, -0.02320098,  0.04514876,  0.02552835],
        [ 0.01898329, -0.03323045,  0.04401389,  0.01882345],
        [ 0.03799133,  0.04815998, -0.02891101,  0.04337117],
        [ 0.00254621, -0.02994119, -0.04806253,  0.02702812]]],
      dtype=float32)

In [12]:
word_vectors[0].flatten()

array([ 0.0003153 , -0.02007775,  0.00180835, -0.0115082 ,  0.02896477,
       -0.04479357, -0.04676715,  0.02114597,  0.01898329, -0.03323045,
        0.04401389,  0.01882345, -0.00077549, -0.00180267,  0.00038796,
       -0.02173099, -0.025114  ,  0.01354594, -0.04560959,  0.00674785],
      dtype=float32)

In [13]:
word_vectors[1].flatten()

array([ 0.04745657, -0.03038027, -0.00270725, -0.02514657,  0.00937791,
       -0.02320098,  0.04514876,  0.02552835,  0.01898329, -0.03323045,
        0.04401389,  0.01882345,  0.03799133,  0.04815998, -0.02891101,
        0.04337117,  0.00254621, -0.02994119, -0.04806253,  0.02702812],
      dtype=float32)

**Build a predictive model which can predict or identify text is about cricket or about chess**

In [ ]:
texts = [
    "I am playing good cricket",
    "He is playing chess",
]

In [ ]:
import numpy as np
sent_levels = np.array([1,0])

In [ ]:
from tensorflow.keras import models, layers

model = models.Sequential()
model.add(layers.Embedding(input_dim = 9 , output_dim = 4, input_length=5))
model.add(layers.Flatten())
model.add(layers.Dense(4))
model.add(layers.Dense(1, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile('adam' , loss='binary_crossentropy' , metrics = ['accuracy'])

In [ ]:
model.fit(padded_sequences , sent_levels , epochs=10)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0000e+00 - loss: 0.7058
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.5000 - loss: 0.7030
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.7001
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6973
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6945
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6917
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.6889
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.6862
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 1.0000 - loss: 0.6834
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 1.0000 - loss: 0.6806


In [ ]:
sent_to_predict = ["I am playing good cricket"]
sentseq = tokenizer.texts_to_sequences(sent_to_predict)
pred_data = pad_sequences(sentseq  , padding='post' , maxlen=5)
pred_data

array([[2, 3, 1, 4, 5]], dtype=int32)

In [ ]:
model.predict(pred_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[0.5066875]], dtype=float32)

In [ ]:
print(int(model.predict(pred_data) > 0.5))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1


/tmp/ipython-input-91-2588463394.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(int(model.predict(pred_data) > 0.5))


**Word2Vec**

**Glove**