In [ ]:
import numpy as np
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import models, layers

In [ ]:
myfile = open('/content/IndiaUS.txt','r')   #Text file handling
mytext = myfile.read()
myfile.close()

In [ ]:
print(mytext)

Following a lavish state visit by Indian Prime Minister Narendra Modi to Washington, US President Joe Biden has called his country's partnership with India among the "most consequential in the world". The BBC's Vikas Pandey and Soutik Biswas explore the factors that contribute to the visit's potential in strengthening the ties between the two nations.

The US's relationship with India - the world's most populous country - is "stronger, closer and more dynamic than any time in history", Mr Biden said at the completion of a pomp-filled state visit by Mr Modi to the White House.

The remark may not be an exaggeration. "This summit suggests that the relationship has been transformed. It underscores just how broad and deep it has become in a relatively short time," says Michael Kugelman of The Wilson Center, an American think-tank.

A key reason is that Washington is keen to draw India closer so that it can act as a counterbalance to China's growing influence in the Indo-Pacific. India-US t

In [ ]:
#Tokenization & Integer encoding
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])

In [ ]:
mytokenizer.word_index

{'the': 1,
 'to': 2,
 'in': 3,
 'a': 4,
 'and': 5,
 'india': 6,
 'of': 7,
 'mr': 8,
 'us': 9,
 'is': 10,
 'modi': 11,
 'has': 12,
 'that': 13,
 'biden': 14,
 'as': 15,
 'with': 16,
 'not': 17,
 "india's": 18,
 'for': 19,
 'but': 20,
 'on': 21,
 'washington': 22,
 'an': 23,
 'it': 24,
 'says': 25,
 'will': 26,
 'are': 27,
 'indian': 28,
 'prime': 29,
 'minister': 30,
 'this': 31,
 'have': 32,
 'trade': 33,
 'visit': 34,
 'by': 35,
 'president': 36,
 'relationship': 37,
 'been': 38,
 'about': 39,
 'strategic': 40,
 'more': 41,
 'up': 42,
 'during': 43,
 'also': 44,
 'make': 45,
 'sirohi': 46,
 'china': 47,
 'air': 48,
 'force': 49,
 'state': 50,
 'his': 51,
 'ties': 52,
 'two': 53,
 'at': 54,
 'white': 55,
 'house': 56,
 'be': 57,
 'lot': 58,
 'ms': 59,
 'technology': 60,
 'jet': 61,
 'semiconductor': 62,
 'now': 63,
 'first': 64,
 'was': 65,
 'global': 66,
 'one': 67,
 'he': 68,
 'without': 69,
 'they': 70,
 'narendra': 71,
 'joe': 72,
 'world': 73,
 'potential': 74,
 'how': 75,
 'becom

In [ ]:
total_words = len(mytokenizer.word_index) + 1
print(total_words)

599


In [ ]:
mytext.split('\n')

['Following a lavish state visit by Indian Prime Minister Narendra Modi to Washington, US President Joe Biden has called his country\'s partnership with India among the "most consequential in the world". The BBC\'s Vikas Pandey and Soutik Biswas explore the factors that contribute to the visit\'s potential in strengthening the ties between the two nations.',
 '',
 'The US\'s relationship with India - the world\'s most populous country - is "stronger, closer and more dynamic than any time in history", Mr Biden said at the completion of a pomp-filled state visit by Mr Modi to the White House.',
 '',
 'The remark may not be an exaggeration. "This summit suggests that the relationship has been transformed. It underscores just how broad and deep it has become in a relatively short time," says Michael Kugelman of The Wilson Center, an American think-tank.',
 '',
 "A key reason is that Washington is keen to draw India closer so that it can act as a counterbalance to China's growing influence 

In [ ]:
a = [[2]]
print(a[0])

[2]


In [ ]:
my_input_sequences = []

for line in mytext.split('\n'):
  #print(line)
  #print(mytokenizer.texts_to_sequences([line])[0])
  token_list = (mytokenizer.texts_to_sequences([line])[0])
  #print(token_list)
  #print(len(token_list))
  for i in range(1,len(token_list)):
    #print(token_list[0:i+1])
    my_n_gram_sequences = token_list[0:i+1]
    my_input_sequences.append(my_n_gram_sequences)

In [ ]:
print(my_input_sequences)

[[99, 4], [99, 4, 177], [99, 4, 177, 50], [99, 4, 177, 50, 34], [99, 4, 177, 50, 34, 35], [99, 4, 177, 50, 34, 35, 28], [99, 4, 177, 50, 34, 35, 28, 29], [99, 4, 177, 50, 34, 35, 28, 29, 30], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14, 12], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14, 12, 178], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14, 12, 178, 51], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14, 12, 178, 51, 100], [99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9,

In [ ]:
max_seq_len = max([len(seq) for seq in my_input_sequences])
input_sequences = pad_sequences(my_input_sequences , maxlen = max_seq_len , padding = 'pre')
print(input_sequences)

[[  0   0   0 ...   0  99   4]
 [  0   0   0 ...  99   4 177]
 [  0   0   0 ...   4 177  50]
 ...
 [  0   0   0 ... 176 598  25]
 [  0   0   0 ... 598  25  59]
 [  0   0   0 ...  25  59  46]]


In [ ]:
print(input_sequences[54])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   1 190]


In [ ]:
#Features for training
X = input_sequences[: , :-1]       #Slicing of a matrix

In [ ]:
X

array([[  0,   0,   0, ...,   0,   0,  99],
       [  0,   0,   0, ...,   0,  99,   4],
       [  0,   0,   0, ...,  99,   4, 177],
       ...,
       [  0,   0,   0, ...,   5, 176, 598],
       [  0,   0,   0, ..., 176, 598,  25],
       [  0,   0,   0, ..., 598,  25,  59]], dtype=int32)

In [ ]:
print(len(X[0]))

82


In [ ]:
#Target
y = input_sequences[: , -1]
y

array([  4, 177,  50, ...,  25,  59,  46], dtype=int32)

In [ ]:
from keras.utils import to_categorical
yt = to_categorical(y , num_classes = total_words)
yt

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
yt[0]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
model = models.Sequential()
model.add(layers.Embedding(input_dim=total_words, output_dim=50, input_length=max_seq_len-1))
model.add(layers.SimpleRNN(82))
model.add(layers.Dense(total_words , activation = 'softmax'))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
X.shape

(1371, 82)

In [ ]:
model.compile(loss = 'categorical_crossentropy' , optimizer='adam' , metrics = ['accuracy'] )
model.fit(X,yt,epochs=100 ,  batch_size=20)

Epoch 1/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - accuracy: 0.1113 - loss: 4.9371
Epoch 2/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.1388 - loss: 4.6235
Epoch 3/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.1718 - loss: 4.3407
Epoch 4/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.2323 - loss: 4.0530
Epoch 5/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - accuracy: 0.2913 - loss: 3.8029
Epoch 6/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 3s 26ms/step - accuracy: 0.3744 - loss: 3.4341
Epoch 7/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.4435 - loss: 3.1966
Epoch 8/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.5217 - loss: 2.9346
Epoch 9/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.6245 - loss: 2.5640
Epoch 10/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - accuracy: 0.6425 - loss: 2.3431
Epoch 11/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - accuracy: 0.7107 - loss: 2.0892
Epoch 12/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step

In [ ]:
'''
review_words = []
for val,id in imdb.get_word_index().items():
  #print(val,id)
  if id in xtrain[0]:
    review_words.append(val)

print(review_words)
'''

In [ ]:
input_text = 'India'
predict_next_words = 30

for k in range(predict_next_words):
  #print(mytokenizer.texts_to_sequences([input_text])[0])
  token_list = mytokenizer.texts_to_sequences([input_text])[0]
  token_list = pad_sequences([token_list] , maxlen = max_seq_len - 1, padding = 'pre')
  #print(token_list)
  predicted = np.argmax(model.predict(token_list) , axis = 1)
  output_word = ""
  for val,id in mytokenizer.word_index.items():
    if id == predicted:
      output_word = val
      break
  input_text += " " + output_word

print(input_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━

**LSTM**

In [ ]:
model_lstm = models.Sequential()
model_lstm.add(layers.Embedding(input_dim=total_words, output_dim=50, input_length=max_seq_len-1))
model_lstm.add(layers.LSTM(82))
model_lstm.add(layers.Dense(total_words , activation = 'softmax'))
model_lstm.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model_lstm.compile(loss = 'categorical_crossentropy' , optimizer='adam' , metrics = ['accuracy'] )
model_lstm.fit(X,yt,epochs=100 ,  batch_size=20)

Epoch 1/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 5s 39ms/step - accuracy: 0.0365 - loss: 6.3018
Epoch 2/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 5s 43ms/step - accuracy: 0.0537 - loss: 5.7679
Epoch 3/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - accuracy: 0.0469 - loss: 5.7474
Epoch 4/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - accuracy: 0.0627 - loss: 5.6415
Epoch 5/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step - accuracy: 0.0668 - loss: 5.4652
Epoch 6/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - accuracy: 0.0496 - loss: 5.5244
Epoch 7/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 6s 45ms/step - accuracy: 0.0710 - loss: 5.3281
Epoch 8/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 5s 39ms/step - accuracy: 0.0669 - loss: 5.2241
Epoch 9/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 5s 39ms/step - accuracy: 0.0745 - loss: 5.0576
Epoch 10/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.0947 - loss: 4.8865
Epoch 11/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 5s 39ms/step - accuracy: 0.1067 - loss: 4.7228
Epoch 12/100
69/69 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step

In [ ]:
input_text = 'India'
predict_next_words = 30

for k in range(predict_next_words):
  #print(mytokenizer.texts_to_sequences([input_text])[0])
  token_list = mytokenizer.texts_to_sequences([input_text])[0]
  token_list = pad_sequences([token_list] , maxlen = max_seq_len - 1, padding = 'pre')
  #print(token_list)
  predicted = np.argmax(model_lstm.predict(token_list) , axis = 1)
  output_word = ""
  for val,id in mytokenizer.word_index.items():
    if id == predicted:
      output_word = val
      break
  input_text += " " + output_word

print(input_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━